"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {api} from "@/lib/api";
import {Heading,Empty,ErrorBox,Badge} from "@/components/ui";
type Metrics={workers:number;active_workers:number;assignments:number;pending_approvals:number;active_mobilizations:number};
type Assignment={id:number;position:string;site:string;status:string};
export default function Dashboard(){
 const [data,setData]=useState<Metrics|null>(null);const [items,setItems]=useState<Assignment[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError("");try{const [m,a]=await Promise.all([api<Metrics>("dashboard"),api<Assignment[]>("assignments")]);setData(m);setItems(a);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 return <main className="page"><Heading label="PUSAT KENDALI" title="Ringkasan operasional" description="Pantau kesiapan tim dan perjalanan penugasan dalam satu tempat."><button className="secondary" onClick={load} disabled={loading}>↻ Perbarui</button><Link className="button" href="/assignments">＋ Buat penugasan</Link></Heading><ErrorBox message={error}/><div className="metric-strip">{[["Total pekerja",data?.workers,"Data personel terdaftar"],["Pekerja aktif",data?.active_workers,"Tersedia dalam registry"],["Menunggu persetujuan",data?.pending_approvals,"Perlu tinjauan approver"],["Mobilisasi berjalan",data?.active_mobilizations,"Terjadwal atau berangkat"]].map(([label,value,note])=><div className="metric" key={String(label)}><span>{label}</span><strong>{loading?"…":value??"—"}</strong><small>{note}</small></div>)}</div><div className="dashboard-grid"><div className="panel"><div className="panel-head"><div><p className="eyebrow">ALUR PENUGASAN</p><h2>Dari rencana ke lapangan</h2></div><Link href="/assignments">Lihat semua →</Link></div><div className="pipeline">{[["draft","Draf"],["submitted","Diajukan"],["approved","Disetujui"],["mobilized","Mobilisasi"],["active","Aktif"]].map(([s,l],i)=><div key={s}><span className="step">0{i+1}</span><strong>{loading?"…":error?"—":items.filter(a=>a.status===s).length}</strong><small>{l}</small></div>)}</div><div className="panel-head"><h2>Penugasan terbaru</h2><span className="muted">{data?.assignments??"—"} total</span></div>{loading?<p className="loading">Memuat penugasan…</p>:items.length?<div className="table-wrap"><table><thead><tr><th>Penugasan</th><th>Lokasi</th><th>Status</th></tr></thead><tbody>{items.slice(-5).reverse().map(a=><tr key={a.id}><td><strong>{a.position}</strong><small>ASN-{String(a.id).padStart(4,"0")}</small></td><td>{a.site}</td><td><Badge status={a.status}/></td></tr>)}</tbody></table></div>:!error&&<Empty title="Perjalanan tim dimulai di sini" description="Tambahkan pekerja, lalu buat penugasan pertama untuk project atau site Anda." href="/workers" label="Buka data pekerja"/>}</div><div className="side-stack"><div className="attention"><p className="eyebrow">PERLU TINDAKAN</p><h2>Jaga proses tetap bergerak.</h2><p>{data?.pending_approvals?data.pending_approvals+" pengajuan menunggu keputusan.":"Tinjau antrean persetujuan sebelum menjadwalkan keberangkatan."}</p><Link href="/approvals">Buka persetujuan →</Link></div><div className="panel quick"><h2>Akses cepat</h2><Link href="/workers"><span>Data & dokumen pekerja<small>Kelola personel dalam organisasi</small></span>↗</Link><Link href="/mobilizations"><span>Jadwal mobilisasi<small>Pantau keberangkatan dan kedatangan</small></span>↗</Link><Link href="/reports"><span>Laporan penugasan<small>Unduh data untuk tim operasional</small></span>↗</Link></div></div></div></main>;
}
