"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { currentOrganization } from "@/lib/auth-headers";
import { Badge, Empty, ErrorBox } from "@/components/ui";

type Worker = { id: number; employee_number: string; full_name: string; status: string };
type Assignment = { id: number; worker_id: number; position: string; site: string; status: string };
type Document = { id: number; status: string };
type Readiness = { ready: boolean; reasons: string[]; document_count: number };

export default function Workers() {
  const [items, setItems] = useState<Worker[]>([]), [assignments, setAssignments] = useState<Assignment[]>([]), [query, setQuery] = useState(""), [filter, setFilter] = useState("all");
  const [error, setError] = useState(""), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [form, setForm] = useState(false), [selected, setSelected] = useState<Worker | null>(null);
  const [documents, setDocuments] = useState<Document[]>([]), [readiness, setReadiness] = useState<Readiness | null>(null);
  async function load() { setLoading(true); setError(""); try { const [people, jobs] = await Promise.all([api<Worker[]>("workers"), api<Assignment[]>("assignments")]); setItems(people); setAssignments(jobs); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(""); try { await api("workers", { method: "POST", body: JSON.stringify({ organization_id: await currentOrganization(), employee_number: data.get("number"), full_name: data.get("name") }) }); setForm(false); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function openProfile(worker: Worker) { setSelected(worker); setReadiness(null); try { const docs = await api<Document[]>(`workers/${worker.id}/documents`); setDocuments(docs); const job = assignments.filter((item) => item.worker_id === worker.id).at(-1); if (job) setReadiness(await api<Readiness>(`assignments/${job.id}/readiness`)); } catch (e) { setError((e as Error).message); } }
  const filtered = items.filter((worker) => (filter === "all" || worker.status === filter) && `${worker.full_name} ${worker.employee_number}`.toLowerCase().includes(query.toLowerCase()));
  const currentJob = selected ? assignments.filter((item) => item.worker_id === selected.id).at(-1) : undefined;
  const score = readiness ? (readiness.ready ? 100 : Math.max(0, 100 - readiness.reasons.length * 20)) : 0;
  return <main className="page">
    <div className="executive-heading"><div><h1>{selected ? "Worker Profile" : "Worker Master"}</h1><p>{selected ? "View worker information, assignment details and readiness status." : "Manage workforce identity, status and mobility records."}</p></div><div className="heading-actions"><button className="secondary" onClick={load}>↻ Refresh</button><button onClick={() => setForm(!form)} aria-expanded={form}>＋ Add Worker</button></div></div>
    <ErrorBox message={error} />
    {form && <form className="panel form-panel" onSubmit={submit}><h2>Register new worker</h2><p className="subtitle">Employee number must be unique inside the organization.</p><div className="form-grid"><label>Employee number<input name="number" required maxLength={50} placeholder="Example: EMP-001" autoFocus /></label><label>Full name<input name="name" required maxLength={160} placeholder="As shown on identity document" /></label></div><div className="form-actions"><button type="button" className="secondary" onClick={() => setForm(false)}>Cancel</button><button disabled={busy}>{busy ? "Saving…" : "Save worker"}</button></div></form>}
    {selected && <section className="panel worker-profile">
      <div className="profile-hero"><div className="profile-avatar">{selected.full_name.split(" ").map((word) => word[0]).slice(0, 2).join("")}</div><div className="profile-meta"><div className="heading-actions"><h2>{selected.full_name}</h2><Badge status={selected.status} /></div><p>Worker ID: {selected.employee_number}</p><p>{currentJob ? `${currentJob.position} · ${currentJob.site}` : "No active assignment"}</p></div><div className="readiness-summary"><small>Readiness Score</small><div className="readiness-ring"><strong>{score}%</strong></div><span>{readiness?.ready ? "Ready to Mobilize" : "Requires Review"}</span></div></div>
      <div className="profile-tabs"><span className="active">Personal Details</span><span>Employment</span><span>Site Assignment</span><Link href="/documents">Documents</Link><Link href="/pre-mob">Pre-Mob</Link></div>
      <div className="data-grid"><div className="data-block"><h3>Personal Information</h3><dl><div><dt>Full Name</dt><dd>{selected.full_name}</dd></div><div><dt>Worker ID</dt><dd>{selected.employee_number}</dd></div><div><dt>Account Status</dt><dd><Badge status={selected.status} /></dd></div></dl></div><div className="data-block"><h3>Employment Details</h3><dl><div><dt>Position</dt><dd>{currentJob?.position || "—"}</dd></div><div><dt>Assignment Status</dt><dd>{currentJob ? <Badge status={currentJob.status} /> : "—"}</dd></div><div><dt>Documents</dt><dd>{documents.length}</dd></div></dl></div><div className="data-block"><h3>Current Assignment</h3><dl><div><dt>Site</dt><dd>{currentJob?.site || "—"}</dd></div><div><dt>Reference</dt><dd>{currentJob ? `ASN-${String(currentJob.id).padStart(4, "0")}` : "—"}</dd></div><div><dt>Readiness</dt><dd>{readiness?.ready ? "Complete" : readiness ? `${readiness.reasons.length} issue(s)` : "Not checked"}</dd></div></dl></div></div>
      <div className="profile-close"><button className="secondary" onClick={() => setSelected(null)}>← Back to workers</button></div>
    </section>}
    <section className="panel"><div className="toolbar"><input aria-label="Search workers" placeholder="Search name or worker ID…" value={query} onChange={(e) => setQuery(e.target.value)} /><select aria-label="Filter status" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><span className="muted">{filtered.length} workers</span></div>{loading ? <p className="loading">Loading workers…</p> : filtered.length ? <div className="table-wrap"><table><thead><tr><th>Worker</th><th>Worker ID</th><th>Latest site</th><th>Status</th><th>Profile</th></tr></thead><tbody>{filtered.map((worker) => { const job = assignments.filter((item) => item.worker_id === worker.id).at(-1); return <tr key={worker.id}><td><div className="row-person"><span className="avatar">{worker.full_name.split(" ").map((word) => word[0]).slice(0, 2).join("")}</span><strong>{worker.full_name}</strong></div></td><td>{worker.employee_number}</td><td>{job?.site || "—"}</td><td><Badge status={worker.status} /></td><td><button className="text-button" onClick={() => void openProfile(worker)}>View profile →</button></td></tr>; })}</tbody></table></div> : !error && <Empty title={items.length ? "No matching workers" : "No workers registered"} description={items.length ? "Try another keyword or filter." : "Add the first worker to begin the workforce registry."} />}</section>
  </main>;
}
