"use client";
import {FormEvent,useEffect,useState} from "react";
import {api} from "@/lib/api";
import {currentOrganization} from "@/lib/auth-headers";
import {Heading,Badge,Empty,ErrorBox} from "@/components/ui";
type Worker={id:number;employee_number:string;full_name:string;status:string};
export default function Workers(){
 const [items,setItems]=useState<Worker[]>([]),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[form,setForm]=useState(false),[selected,setSelected]=useState<Worker|null>(null);
 async function load(){setLoading(true);setError("");try{setItems(await api<Worker[]>("workers"));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError("");try{await api("workers",{method:"POST",body:JSON.stringify({organization_id:await currentOrganization(),employee_number:data.get("number"),full_name:data.get("name")})});setForm(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const filtered=items.filter(w=>(filter==="all"||w.status===filter)&&(w.full_name+" "+w.employee_number).toLowerCase().includes(query.toLowerCase()));
 return <main className="page"><Heading label="PERSONEL" title="Data pekerja" description="Kelola identitas, status, dan data personel organisasi Anda."><button className="secondary" onClick={load}>↻ Perbarui</button><button onClick={()=>setForm(!form)} aria-expanded={form}>＋ Tambah pekerja</button></Heading><ErrorBox message={error}/>{form&&<form className="panel form-panel" onSubmit={submit}><h2>Daftarkan pekerja baru</h2><p className="subtitle">Nomor pekerja harus unik. Data dapat ditinjau setelah disimpan.</p><div className="form-grid"><label>Nomor pekerja<input name="number" required maxLength={50} placeholder="Contoh: EMP-001" autoFocus/></label><label>Nama lengkap<input name="name" required maxLength={160} placeholder="Sesuai identitas pekerja"/></label></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setForm(false)}>Batal</button><button disabled={busy}>{busy?"Menyimpan…":"Simpan pekerja"}</button></div></form>}<div className="panel"><div className="toolbar"><input aria-label="Cari pekerja" placeholder="Cari nama atau nomor pekerja…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select><span className="muted">{filtered.length} pekerja</span></div>{selected&&<div className="detail"><div className="panel-head"><h2>Profil pekerja</h2><button className="secondary" onClick={()=>setSelected(null)}>Tutup</button></div><dl><div><dt>Nama lengkap</dt><dd>{selected.full_name}</dd></div><div><dt>Nomor pekerja</dt><dd>{selected.employee_number}</dd></div><div><dt>Status</dt><dd><Badge status={selected.status}/></dd></div></dl></div>}{loading?<p className="loading" role="status">Memuat data pekerja…</p>:filtered.length?<div className="table-wrap"><table><thead><tr><th>Pekerja</th><th>Nomor pekerja</th><th>Status</th><th>Detail</th></tr></thead><tbody>{filtered.map(w=><tr key={w.id}><td><div className="row-person"><span className="avatar">{w.full_name.slice(0,2).toUpperCase()}</span><strong>{w.full_name}</strong></div></td><td>{w.employee_number}</td><td><Badge status={w.status}/></td><td><button className="text-button" onClick={()=>setSelected(w)}>Lihat profil →</button></td></tr>)}</tbody></table></div>:!error&&<Empty title={items.length?"Tidak ada hasil pencarian":"Belum ada pekerja terdaftar"} description={items.length?"Coba kata kunci atau filter lain.":"Pilih Tambah pekerja untuk mulai membangun registry organisasi."}/>}</div></main>;
}
