"use client";
import {FormEvent,useEffect,useState} from "react";
import {api} from "@/lib/api";
import {Heading,Badge,Empty,ErrorBox} from "@/components/ui";
type Assignment={id:number;worker_id:number;position:string;site:string;status:string};
type Worker={id:number;full_name:string;status:string};
export default function Assignments(){
 const [items,setItems]=useState<Assignment[]>([]),[workers,setWorkers]=useState<Worker[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[form,setForm]=useState(false),[query,setQuery]=useState("");
 async function load(){setError("");setLoading(true);try{const [a,w]=await Promise.all([api<Assignment[]>("assignments"),api<Worker[]>("workers")]);setItems(a);setWorkers(w);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);try{await api("assignments",{method:"POST",body:JSON.stringify({worker_id:Number(d.get("worker")),position:d.get("position"),site:d.get("site")})});setForm(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="page"><Heading label="PENEMPATAN" title="Penugasan tim" description="Hubungkan pekerja dengan posisi dan lokasi penempatan."><button onClick={()=>setForm(!form)} aria-expanded={form}>＋ Buat penugasan</button></Heading><ErrorBox message={error}/>{form&&<form className="panel form-panel" onSubmit={submit}><h2>Penugasan baru</h2><div className="form-grid"><label>Pekerja aktif<select name="worker" required><option value="">Pilih pekerja</option>{workers.filter(w=>w.status==="active").map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Posisi<input name="position" required maxLength={120} placeholder="Contoh: Operator"/></label><label>Project / site<input name="site" required maxLength={160} placeholder="Nama lokasi penempatan"/></label></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setForm(false)}>Batal</button><button disabled={busy}>{busy?"Menyimpan…":"Simpan penugasan"}</button></div></form>}<div className="panel"><div className="toolbar"><input aria-label="Cari penugasan" placeholder="Cari posisi atau site…" value={query} onChange={e=>setQuery(e.target.value)}/><span className="muted">{items.length} penugasan</span></div>{loading?<p className="loading">Memuat penugasan…</p>:items.length?<div className="table-wrap"><table><thead><tr><th>Referensi</th><th>Pekerja</th><th>Posisi</th><th>Site</th><th>Status</th></tr></thead><tbody>{items.filter(a=>(a.position+" "+a.site).toLowerCase().includes(query.toLowerCase())).map(a=><tr key={a.id}><td>ASN-{String(a.id).padStart(4,"0")}</td><td><strong>{workers.find(w=>w.id===a.worker_id)?.full_name||"#"+a.worker_id}</strong></td><td>{a.position}</td><td>{a.site}</td><td><Badge status={a.status}/></td></tr>)}</tbody></table></div>:!error&&<Empty title="Belum ada penugasan" description="Daftarkan pekerja aktif, lalu pilih Buat penugasan untuk menentukan posisi dan site." href="/workers" label="Kelola pekerja"/>}</div></main>;
}
